[package]
name = "tully"
version = "0.1.0"
authors = ["Santhosh <santhoshkumarr1096@gmail.com>"]
edition = "2018"
#![feature(backtrace)]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
